from pathlib import Path
import sys

# Make repo root importable
sys.path.append(str(Path(__file__).resolve().parents[1]))

from src.youtube.scraper import scrape_monthly_top50

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "assets"; ASSETS.mkdir(parents=True, exist_ok=True)
DATA   = ROOT / "data";   DATA.mkdir(parents=True, exist_ok=True)

CSV   = ASSETS / "yt_counter_strike_monthly_top50.csv"
STATE = ASSETS / "yt_counter_strike_monthly_state.json"
TOKENS = DATA / "tokens.json"  # generated by separate OAuth script

if __name__ == "__main__":
    rows = scrape_monthly_top50(
        start="2005-07",          # inclusive
        end="2025-10",            # exclusive (runs through Sept 2025)
        query="counter strike",
        csv_path=CSV,
        state_path=STATE,
        tokens_path=TOKENS,
        batch_size=50,
    )
    print(f"Finished. Total rows written: {rows}")
